---
title: "Midterm Review"
subtitle: "EC 320: Introduction to Econometrics"
date: "Winter 2022"
output:
  xaringan::moon_reader:
    css: ['default', 'metropolis', 'metropolis-fonts', 'my-css.css']
    # self_contained: true
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: inverse, middle

```{r Setup, include = F}
options(htmltools.dir.version = FALSE)
library(pacman)
# devtools::install_github("dill/emoGG")
library(pacman)
p_load(
  broom, here, tidyverse,
  emoGG, latex2exp, ggplot2, ggthemes, viridis, extrafont, gridExtra,
  kableExtra,
  data.table, dagitty, ggdag,
  dplyr, gganimate,
  lubridate,
  magrittr, knitr, parallel
)
# Define colors
red_pink <- "#e64173"
met_slate <- "#23373b" # metropolis font color
# Notes directory
dir_slides <- "~/GitHub/EC320_Econometrics/Lectures/06-Midterm_Review/"
# Knitr options
opts_chunk$set(
  comment = "#>",
  fig.align = "center",
  fig.height = 7,
  fig.width = 10.5,
  #dpi = 300,
  #cache = T,
  warning = F,
  message = F
)  
theme_simple <- theme_bw() + theme(
  axis.line = element_line(color = met_slate),
  panel.grid = element_blank(),
  rect = element_blank(),
  strip.text = element_blank(),
  text = element_text(family = "Fira Sans", color = met_slate, size = 14),
  axis.text.x = element_text(size = 12),
  axis.text.y = element_text(size = 12),
  axis.ticks = element_blank(),
  plot.title = element_blank(),
  legend.position = "none"
)
theme_gif <- theme_bw() + theme(
  axis.line = element_line(color = met_slate),
  panel.grid = element_blank(),
  rect = element_blank(),
  strip.text = element_blank(),
  text = element_text(family = "Fira Sans", color = met_slate, size = 14),
  axis.text.x = element_text(size = 12),
  axis.text.y = element_text(size = 12),
  axis.ticks = element_blank()
)
```

# Prologue

---
# Housekeeping


Midterm 1 on Wednesday

- No lab this week

Problem Set 1 solution posted

---
# Grades

## Exercises

.hi[Kyu is the person of contact]

- [kyutarom@uoregon.edu](mailto:kyutarom@uoregon.edu)
- Zoom

**Q:** Why? <br>
**A:** To ensure *consistency in grading.*

## Problem sets and exams

.hi[I am the person of contact]

- [bchang@uoregon.edu](mailto:bchang@uoregon.edu)
- PLC 420

---
class: inverse, middle

# Midterm I: High Concepts

---
# Midterm Topics

.green[Anything from the lectures, labs, or problem sets] .hi-green[is fair game!]

1. Probability Theory

2. Statistics

3. The Fundamental Problem of Econometrics

4. Randomized Control Trials

5. The Logic of Regression

6. Tidy Data and .mono[R] (bonus points)

---
# Midterm Topics

## 1. Probability Theory

Random variables

- Sketch out the probability distribution of a random variable.

Expected values

Population variance

---
# Midterm Topics

## 2. Statistics

Estimators

- Population *v.s.* sample distinction.
- Sample mean, sample variance, sample covariance, sample correlation coefficient.
- Unbiasedness and efficiency.

Hypothesis testing

- Statistical significance.
- $t$-statistics.
- Two-sided $t$ tests using rule of thumb discussed in class (*i.e.,* compare $t$ to $t_{\text{crit}} = 2$).

---
# Midterm Topics

## 3. The Fundamental Problem of Econometrics

Causal mechanisms *v.s.* confounding factors

Ideal data on potential outcomes

- Individual *v.s.* average treatment effects.
- Difference-in-means based on observable data.

Selection bias

---
# Midterm Topics

## 4. Randomized Control Trials

How do RCTs eliminate selection bias?

- Can an RCT fail to eliminate selection bias? How?

--

Research questions

- Identify outcome variable and treatment variable.

Estimation using experimental data

- Difference-in-means.
- Linear regression.

---
# Midterm Topics

## 5. The Logic of Regression

Regression models

- Identify outcome variable, treatment variable, and control variables.

Estimation using OLS

- How does OLS adjust treatment effect estimates for confounding factors?

---
# Midterm Topics

## 5. The Logic of Regression (cont.)

Omitted variables

- When does omitting a variable cause omitted-variable bias?
- Illustrate assumptions with causal diagrams.

Regression tables

- Write down model.
- Calculate omitted-variable bias.

---
# Midterm Topics

## 6. Tidy Data and .mono[R]

For earning bonus points! [will be either multiple choice question or true/false question]

Identify .mono[R] functions

- What does the function do?
- I will only ask you about functions you've seen in lab.
- .hi[I will not ask you to write code.]

Which one of the following code produce below output?

- Example: Console output of .mono[filter()] or .mono[select()].

---
# Midterm Structure

## Multiple Choice

- 5 questions
- 6 points per question (30 points total)

## True or False

- 5 questions
- 6 points per question (30 points total)
- ~~Brief explanations required for full credit~~

## Free Response

- 5 multi-part questions with varying numbers of points (50 points total)
- Explanations required for full credit

---
# Midterm Protocol

## Materials

- Writing utensil
- 3-inch-by-5-inch note card
- Basic or scientific calculator (no graphing or programming capabilities)
- .hi[Nothing else]

## Procedure

- 80 minutes from *"you may begin"* to *"pencils down"*
- First 30 minutes: .hi[quiet period] (no questions, no getting up)
- Last 50 minutes: ask lots of questions


